apiVersion: v1
kind: Service
metadata:
  name: {{ include "piggymetrics.fullname" . }}
  labels: 
    {{- include "piggymetrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
  selector: 
    {{- include "piggymetrics.labels" . | nindent 4 }}
  

