steps:
  - name: gcr.io/cloud-builders/docker
    id  : $SERVICE-build
    args: ['build', '-t', 'us-central1-docker.pkg.dev/devops-workshop-2023/piggymetrics/$FOLDER$SERVICE:$VERSION', './$SERVICE']

  - name: gcr.io/cloud-builders/docker
    id  : $SERVICE-push
    args: ['push', 'us-central1-docker.pkg.dev/devops-workshop-2023/piggymetrics/$FOLDER$SERVICE:$VERSION']
