envvars:
  CONFIG_SERVICE_PASSWORD: password
  NOTIFICATION_SERVICE_PASSWORD: password
  STATISTICS_SERVICE_PASSWORD: password
  ACCOUNT_SERVICE_PASSWORD: password
  MONGODB_PASSWORD: password

statefulset:
  enabled: true

image:
  repository: us-central1-docker.pkg.dev/devops-workshop-2023/piggymetrics/snapshots/mongodb
  pullPolicy: IfNotPresent
replicaCount: 1

spec:
  storage: 4Gi
  storageClassName: standard-rwo

service:
  type: ClusterIP
  port: 25000
  targetport: 27017

containers:
  name: authmongodb

imagePullSecrets: []
nameOverride: "authmongodb"
fullnameOverride: "auth-mongodb"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
