envvars:
  CONFIG_SERVICE_PASSWORD: password
  NOTIFICATION_SERVICE_PASSWORD: password
  STATISTICS_SERVICE_PASSWORD: password
  ACCOUNT_SERVICE_PASSWORD: password
  MONGODB_PASSWORD: password

statefulset:
  enabled: false

image:
  repository: us-central1-docker.pkg.dev/devops-workshop-2023/piggymetrics/snapshots/config
  pullPolicy: IfNotPresent
replicaCount: 1

service:
  type: ClusterIP
  port: 8888
  targetport: 8888

containers:
  name: config

imagePullSecrets: []
nameOverride: "config"
fullnameOverride: "config"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
