envvars:
  CONFIG_SERVICE_PASSWORD: password
  NOTIFICATION_SERVICE_PASSWORD: password
  STATISTICS_SERVICE_PASSWORD: password
  ACCOUNT_SERVICE_PASSWORD: password
  MONGODB_PASSWORD: password

statefulset:
  enabled: false

image:
  repository: us-central1-docker.pkg.dev/devops-workshop-2023/piggymetrics/snapshots/turbine-stream-service
  pullPolicy: IfNotPresent
replicaCount: 1


service:
  type: ClusterIP
  port: 8989
  targetport: 8989

containers:
  name: turbine-stream-service

imagePullSecrets: []
nameOverride: "turbine-stream-service"
fullnameOverride: "turbine-stream-service"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
